# Generated by Django 4.1.1 on 2022-10-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
