# Generated by Django 4.1.7 on 2023-03-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_state_slug_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
