version: '3.8'

services:
  web:
    build: 
      context: ./backend/
      dockerfile: Dockerfile_new
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - redis
    #   - db
    container_name: backend-server

  worker:
    build: ./backend/
    command: celery -A backend worker --loglevel=info --logfile=logs/celery.log
    volumes:
      - ./backend/:/usr/src/app
    env_file:
      - .env
    depends_on:
      - web
      - redis
    container_name: backend-celery-worker
    
  dashboard:
    build: ./backend/
    command: celery flower -A backend --port=5555 --broker=redis://redis:6379/0
    ports:
      - 5555:5555
    env_file:
      - .env
    depends_on:
      - web
      - redis
      - worker


  # db:
  #   image: postgres
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - ./database:/var/lib/postgresql/data
  #   environment:      
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=136900
  #     - POSTGRES_DB=dockerdb
  #   container_name: backend-db

    
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    container_name: backend-redis