# Generated by Django 4.1.9 on 2023-05-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=120)),
                ('address', models.CharField(max_length=250)),
            ],
        ),
    ]
