# Generated by Django 3.2.8 on 2022-12-02 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='history',
            new_name='string',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='Total',
            new_name='total',
        ),
    ]
