# Generated by Django 4.1.7 on 2023-03-26 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=120, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('age', models.PositiveSmallIntegerField()),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('married', models.CharField(choices=[('M', 'Married'), ('U', 'Unmarried')], default='U', max_length=1)),
                ('alien', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
