# Generated by Django 4.1.7 on 2023-03-26 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='human/%Y/%d/%m'),
        ),
    ]
