# Generated by Django 4.1.7 on 2023-03-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
        ('human', '0002_human_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='address',
            field=models.ManyToManyField(to='info.address'),
        ),
    ]
