# Generated by Django 4.1.7 on 2023-03-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
        ('human', '0003_human_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='address',
            field=models.ManyToManyField(related_name='human', to='info.address'),
        ),
    ]
