# Generated by Django 4.1.7 on 2023-03-26 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0004_alter_human_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='human',
            options={'get_latest_by': '-created', 'ordering': ['username'], 'verbose_name': 'human'},
        ),
    ]
