# Generated by Django 4.1.7 on 2023-03-26 14:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0006_school_human_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
