# Generated by Django 4.1.7 on 2023-03-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
        ('human', '0007_school_created_school_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='address',
            field=models.ManyToManyField(blank=True, null=True, related_name='school', to='info.address'),
        ),
    ]
