# Generated by Django 4.1.3 on 2022-11-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('subject', models.CharField(blank=True, max_length=120, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('slug', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('SNT', 'Sent'), ('PND', 'Pending')], default='PND', max_length=3)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sent', models.DateTimeField(auto_now=True)),
                ('delivered', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
