# Generated by Django 4.1.3 on 2022-11-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='delivered',
        ),
        migrations.AlterField(
            model_name='letter',
            name='status',
            field=models.CharField(choices=[('PND', 'Traveling'), ('SNT', 'Sent'), ('TRV', 'Traveling'), ('DLV', 'Deliered')], default='PND', max_length=3),
        ),
    ]
