# Generated by Django 4.1.5 on 2023-02-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strawberry_app', '0002_color_alter_fruit_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='color',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
